package fr.nimbus.core.managers;

import fr.nimbus.api.middleware.Middleware;
import fr.nimbus.api.middleware.MiddlewareResult;
import fr.nimbus.api.middleware.RequestContext;

import java.util.ArrayList;
import java.util.List;

public class MiddlewareManager {
    private final List<Middleware> globalMiddlewares = new ArrayList<>();

    /**
     * Registers a global middleware.
     *
     * @param middleware The middleware to register.
     */
    public void registerMiddleware(Middleware middleware) {
        globalMiddlewares.add(middleware);
    }

    /**
     * Dynamically loads a middleware by its class type.
     * This can also be replaced with custom scanning logic.
     *
     * @param middlewareClass The middleware class to instantiate.
     * @return The middleware instance.
     * @throws Exception If instantiation fails.
     */
    public Middleware loadMiddleware(Class<? extends Middleware> middlewareClass) throws Exception {
        return middlewareClass.getDeclaredConstructor().newInstance();
    }

    /**
     * Executes all global middlewares before the controller processes the request.
     *
     * @param request The current HTTP request context.
     * @return A MiddlewareResult indicating if the request should continue or stop execution.
     */
    public MiddlewareResult executeBefore(RequestContext request) {
        for (Middleware middleware : globalMiddlewares) {
            MiddlewareResult result = middleware.before(request);
            if (result != null && !result.shouldProceed()) {
                return result; // Stop if a middleware blocks the request
            }
        }
        return new MiddlewareResult(true, null); // Continue processing the request
    }

    /**
     * Executes all global middlewares after the controller processes the request.
     *
     * @param response The response object generated by the controller.
     * @param request  The current HTTP request context.
     * @return The final (possibly modified) response object.
     */
    public Object executeAfter(Object response, RequestContext request) {
        for (Middleware middleware : globalMiddlewares) {
            response = middleware.after(response, request);
        }
        return response;
    }
}