package fr.nimbus.api.middleware;

/**
 * Middleware interface provides mechanisms for handling HTTP requests
 * and responses within an application framework. Middleware objects
 * implementing this interface can intercept, process, or modify
 * requests and responses at different stages of their lifecycle to enable
 * functionalities such as authentication, logging, or request transformation.
 */
public interface Middleware {
    /**
     * Intercepts a request before it reaches the controller.
     *
     * @param request The current HTTP request.
     * @return A MiddlewareResult indicating whether to proceed or stop execution.
     */
    MiddlewareResult before(RequestContext request);

    /**
     * Intercepts the response after it has been generated by the controller.
     *
     * @param response The response object generated by the controller.
     * @return The modified or unchanged response object.
     */
    Object after(Object response, RequestContext request);

    /**
     * Determines if this middleware applies to a given request.
     *
     * @param request The current HTTP request context.
     * @return True if the middleware should be applied, false otherwise.
     */
    boolean appliesTo(RequestContext request);
}